### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by gidra5** [Miroso02/Neural-network-polynomials#3]
https://github.com/Miroso02/Neural-network-polynomials/blob/6f9116b4d4f11095f307af76469a0ad0da71ff60/src/Main.js#L21

`help()` можно не выделять в отдельную функцию, а выводить один раз при запуске,тут не так уж и много комманд, что бы засрать консоль

https://github.com/Miroso02/Neural-network-polynomials/blob/6f9116b4d4f11095f307af76469a0ad0da71ff60/src/Main.js#L30

Можно без блока обьявить в одну строку, менее громоздко будет.

https://github.com/Miroso02/Neural-network-polynomials/blob/6f9116b4d4f11095f307af76469a0ad0da71ff60/src/Main.js#L33

Выделять в функцию бесполезно ибо ты её больше нигде не юзанешь, можно заменить кодом самой функции.

https://github.com/Miroso02/Neural-network-polynomials/blob/6f9116b4d4f11095f307af76469a0ad0da71ff60/src/Main.js#L59

Так же с `trainingInput()`.

https://github.com/Miroso02/Neural-network-polynomials/blob/6f9116b4d4f11095f307af76469a0ad0da71ff60/src/Main.js#L89

Можно поставить перед `trainingInput()`

https://github.com/Miroso02/Neural-network-polynomials/blob/6f9116b4d4f11095f307af76469a0ad0da71ff60/src/Main.js#L100

Думаю можно упростить структуру колбека, обьеденив одинаковые case'ы и ожидая сразу вместе с буквой параметры (например `f 5 0 1` будет значить что ты вводишь функцию с такими коэфициентами, аналогично с `t` и  `c`), вместе с этим можно избавиться от переменной `consoleMode`

Гайд для инпута многочлена можно писать в хелпе к этому параметру

**Comment by miroso22** [comment]
Последнее решил не менять, ибо это сильно усложняет ввод с консоли
